jenkinsci/validating-yaml-parameter-plugin

- pom.xml
Updating jenkins-core required version and some dependencies with vulnerabilities.
> fix: update dependencies in pom.xml due to vulnerabilities

- Jenkinsfile
> fix: update Jenkinsfile to use container and and build java 8 & 11

- pom.xml
> fix: bump version to 1.4

- pom.xml
> fix: correct version of plugin

- pom.xml
> fix: update pom.xml

- pom.xml
> fix: set correct version to release

- pom.xml
> fix: incrementalify

- .github/workflows/maven.yml
- pom.xml
> Fix dependencies 1

- .github/release-drafter.yml
- pom.xml
> fix: update snakeyaml version to 1.32

- pom.xml
> fix: increase version

- .github/release-drafter.yml
- pom.xml
> fix: revert changes

- pom.xml
Updated dependency list and remove optional for rebuilder dependency
> fix: re-place the dependencies and make rebuilder required.

- .github/release-drafter.yml
- .gitignore
- pom.xml
- src/test/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterDefinitionTest.java
A few minor fixes to restore the CD action and miscellaneous pom updates.
> fix: Erroneous configured CD workflow and misc pom stuff

- pom.xml
> fix: increase jenkins requirements to 2.346.3

- .github/release-drafter.yml
> fix: remove release drafter

- Jenkinsfile
> fix: run linux java-17 tests execution

- CONTRIBUTING.md
This is to simply add a CONTRIBUTING.md file to increase plugin score.
> feat: add a contributing guide

- src/main/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterDefinition.java
- src/main/java/io/jenkins/plugins/validating_yaml_parameter/ValidationResult.java
Plugins version 4.77 requires to pass some SPOTBUGS checks. This is to prepare the code for it.
> fix: set attributes private to prepare compatibility with 4.77 plugins

- pom.xml
- reference https://github.com/jenkinsci/validating-yaml-parameter-plugin/pull/134
Unit tests
> fix: use jenkins.baseline as proposed by @strangelookingnerd

- .github/CODEOWNERS
This is to increase the health checks
> fix: add CODEOWNERS

- pom.xml
- src/test/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterDefinitionTest.java
- src/test/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterValueTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
> Migrate tests to JUnit5

- pom.xml
- src/main/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterDefinition.java
- src/main/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterValue.java
- src/test/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterDefinitionTest.java
Jenkins 2.479.1 provides Jakarta EE 9, Eclipse Jetty 12, Spring Security 6, and Java 17.
* Remove deprecations
* Use Java 17 language features
* Minor cleanup
`mvn clean verify`
> Require 2.479.1 or newer

- pom.xml
- src/main/resources/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterDefinition/config.jelly
- src/test/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterDefinitionTest.java
- src/test/java/io/jenkins/plugins/validating_yaml_parameter/ValidatingYamlParameterValueTest.java
- src/test/java/io/jenkins/plugins/validating_yaml_parameter/ValidationResultTest.java
I wanted to test how good Cursor is at creating tests.  This seems ok, test coverage increased.
yes
> feat: increase test coverage
